# wrangler.toml
name = 'hilltop-website'
compatibility_date = "2026-08-02"

[assets]
directory = "dist"

# Your D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "hilltop_website"
database_id = "34e53829-3931-4d4b-9ba7-abac636d1671"